name: CI

on: [push]

#env:
#  DEPLOY_PATH: /var/www/html/deploy_test2
#  # В теории можно собрать не только Vue-приложение, так как принцип сборки мало где отличается
#  BUILD_SCRIPT: npm run build
#  BUILD_SCRIPT_OUTPUT: /dist

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Делаем checkout текущей ветки
      - uses: actions/checkout@v2
      # Устанавливаем Node.JS для сборки приложения
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      # Записываем в переменные окружения имя текущей ветки

      # Устанавливаем зависимости для сборки
      - name: Install Dependencies
        run: npm i
      # Собираем приложение
      - name: ssh
        # Authorize SSH Host
        run: mkdir -p /root/.ssh && \
        run: chmod 0700 /root/.ssh && \
        run: ssh-keyscan github.com > /root/.ssh/known_hosts

      # Add the keys and set permissions
        run: echo "$ssh_prv_key" > /root/.ssh/id_rsa && \
        run: echo "$ssh_pub_key" > /root/.ssh/id_rsa.pub && \
        run: chmod 600 /root/.ssh/id_rsa && \
        run: chmod 600 /root/.ssh/id_rsa.pub
        
      - name: Build Appliction
        run: npm run build
      # Доставляем собранное приложение на сервер
      #- name: Deploy to Server
      #  uses: appleboy/scp-action@master
      #  with:
      #    host: '185.244.172.89'
      #    port: '22'
      #    username: 'root'
      #    key: '50fx9voVOgv3'
      #    strip_components: 1
      #    source: /dist
      #    target: "/var/www/html/deploy_test2/"
      - name: Deploy Files
        uses: appleboy/scp-action@master
        env:
          HOST: '185.244.172.89'
          USERNAME: 'root'
          KEY: ${{secrets.SSH_PRIVATE_KEY}}
        with:
          source: dist
          target: "/var/www/html/deploy_test2"
          strip_components: 1
      - name: Print Info
        run: echo "Deployed at 185.244.172.89/deploy_test2/"